# Generated by Django 5.2.17 on 2026-09-06 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(db_index=True)),
                ('inventory_type', models.CharField(choices=[('ROOM', 'Room Inventory'), ('EXPERIENCE', 'Experience Slot')], max_length=20)),
                ('inventory_id', models.CharField(db_index=True, max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed / Booked'), ('EXPIRED', 'Expired'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
