# Generated by Django 5.2.17 on 2026-09-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryhold',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='itinerary_version_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryhold',
            name='booking_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhold',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed / Booked'), ('CONSUMED', 'Consumed / Booked'), ('EXPIRED', 'Expired'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
