# Generated by Django 5.2.17 on 2026-09-06 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('trip_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers_count', models.PositiveIntegerField(default=2)),
                ('primary_guest_name', models.CharField(max_length=150)),
                ('primary_guest_phone', models.CharField(max_length=20)),
                ('primary_guest_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_FAILED', 'Payment Failed'), ('CONFIRMED', 'Confirmed'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('green_trip_score', models.PositiveIntegerField(default=85)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('ROOM', 'Room Stay'), ('EXPERIENCE', 'Local Experience'), ('TRANSPORT', 'Chauffeur Transport'), ('PACKAGE', 'Curated Package')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('units', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_org_id', models.UUIDField(db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
            ],
        ),
    ]
