# Generated by Django 5.2.17 on 2026-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_digital_pass_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when traveler details were anonymized.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='retention_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Statutory tax & financial record retention deadline.', null=True),
        ),
    ]
