services:
  - type: web
    name: keralink-api
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements/base.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: JWT_SIGNING_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
