# Generated by Django 5.2.17 on 2026-09-06 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('destination_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.FloatField()),
                ('max_group_size', models.PositiveIntegerField(default=10)),
                ('hero_image', models.URLField()),
                ('included_items', models.JSONField(default=list)),
                ('meeting_point', models.CharField(max_length=255)),
                ('host_name', models.CharField(max_length=128)),
                ('host_role', models.CharField(max_length=128)),
                ('rating', models.FloatField(default=4.9)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=True)),
                ('rain_friendly', models.BooleanField(default=False)),
                ('rain_alternative_id', models.CharField(blank=True, max_length=64, null=True)),
                ('explanation', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('total_capacity', models.PositiveIntegerField(default=10)),
                ('booked_capacity', models.PositiveIntegerField(default=0)),
                ('held_capacity', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='experiences.experience')),
            ],
        ),
    ]
