# Generated by Django 5.2.17 on 2026-09-06 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('destination_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BOUTIQUE_RESORT', 'Boutique Resort'), ('LUXURY_HOUSEBOAT', 'Luxury Houseboat'), ('HERITAGE_HOMESTAY', 'Heritage Homestay'), ('ECO_LODGE', 'Eco Lodge'), ('CLIFF_VILLA', 'Cliff Villa')], max_length=50)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hero_image', models.URLField()),
                ('star_rating', models.PositiveIntegerField(default=5)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eco_green_score', models.PositiveIntegerField(default=85)),
                ('amenities', models.JSONField(default=list)),
                ('ai_suitability_score', models.PositiveIntegerField(default=95)),
                ('explanation', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('features', models.JSONField(default=list)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='accommodations.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_rooms', models.PositiveIntegerField(default=5)),
                ('booked_rooms', models.PositiveIntegerField(default=0)),
                ('held_rooms', models.PositiveIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accommodations.roomtype')),
            ],
        ),
    ]
