# Generated by Django 5.2.17 on 2026-10-02 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('operator_phone', models.CharField(max_length=30)),
                ('operator_whatsapp', models.CharField(max_length=30)),
                ('operator_license', models.CharField(blank=True, default='DTPC / Kerala Tourism Accredited', max_length=100)),
                ('is_operator_verified', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('HILL_STATION', 'Misty Hill Stations & Tea Trails'), ('BACKWATERS', 'Backwaters & Houseboat Cruises'), ('HONEYMOON', 'Romantic Honeymoon Escapes'), ('ADVENTURE', 'Wildlife Safari & Adventure Treks'), ('AYURVEDA', 'Ayurvedic Wellness & Yoga'), ('CULTURE', 'Heritage, Kathakali & Temple Arts'), ('FAMILY', 'Complete Family Circuits')], db_index=True, default='HILL_STATION', max_length=50)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('duration_nights', models.PositiveIntegerField(default=2)),
                ('start_city', models.CharField(default='Kochi', max_length=100)),
                ('end_city', models.CharField(default='Kochi', max_length=100)),
                ('destinations_covered', models.JSONField(default=list)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hero_image', models.URLField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=list)),
                ('rating', models.FloatField(default=4.9)),
                ('review_count', models.PositiveIntegerField(default=24)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('traveler_name', models.CharField(max_length=150)),
                ('traveler_email', models.EmailField(blank=True, default='', max_length=254)),
                ('traveler_phone', models.CharField(max_length=30)),
                ('travel_date', models.CharField(blank=True, default='', max_length=50)),
                ('guests_count', models.PositiveIntegerField(default=2)),
                ('message', models.TextField(blank=True, default='')),
                ('channel', models.CharField(default='INQUIRY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
