# Generated by Django 5.2.17 on 2026-09-06 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('aggregate_type', models.CharField(db_index=True, max_length=64)),
                ('aggregate_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed / Dispatched'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('consumer_name', models.CharField(db_index=True, max_length=128)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
