# Generated by Django 5.2.17 on 2026-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboxevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed / Dispatched'), ('FAILED', 'Failed / Retrying'), ('DEAD_LETTER', 'Dead Letter / Max Retries Exceeded')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
