# Generated by Django 5.2.17 on 2026-09-06 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlanAnalyticsMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('generated_plans_count', models.PositiveIntegerField(default=0)),
                ('accepted_plans_count', models.PositiveIntegerField(default=0)),
                ('regenerated_plans_count', models.PositiveIntegerField(default=0)),
                ('average_synthesis_time_ms', models.FloatField(default=450.0)),
            ],
        ),
        migrations.CreateModel(
            name='TripProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=6)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('starting_location', models.CharField(default='Kochi', max_length=128)),
                ('ending_location', models.CharField(blank=True, max_length=128, null=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=80000.0, max_digits=12)),
                ('travel_style', models.CharField(choices=[('BUDGET', 'Budget'), ('COMFORT', 'Comfort'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], default='PREMIUM', max_length=20)),
                ('pace', models.CharField(choices=[('RELAXED', 'Relaxed'), ('BALANCED', 'Balanced'), ('PACKED', 'Packed')], default='RELAXED', max_length=20)),
                ('interests', models.JSONField(default=list)),
                ('avoidances', models.JSONField(default=list)),
                ('raw_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='FINALIZED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='ai.tripprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AIPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('change_reason', models.CharField(max_length=255)),
                ('itinerary_payload', models.JSONField()),
                ('pricing_payload', models.JSONField()),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('total_travel_hours', models.FloatField(default=0.0)),
                ('green_trip_score', models.PositiveIntegerField(default=88)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai.aiplan')),
            ],
            options={
                'unique_together': {('plan', 'version_number')},
            },
        ),
    ]
