# Generated by Django 5.2.17 on 2026-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripprofile',
            name='monsoon_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripprofile',
            name='month',
            field=models.CharField(default='October', max_length=32),
        ),
        migrations.AlterField(
            model_name='tripprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
