# Generated by Django 5.2.17 on 2026-09-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_tripprofile_monsoon_mode_tripprofile_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplanversion',
            name='changed_events',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aiplanversion',
            name='diff_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='aiplanversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='ai.aiplanversion'),
        ),
        migrations.AddField(
            model_name='aiplanversion',
            name='route_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='aiplanversion',
            name='validation_result',
            field=models.JSONField(default=dict),
        ),
    ]
