# Generated by Django 5.2.17 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiplanversion_changed_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplanversion',
            name='validation_status',
            field=models.CharField(default='VALID', max_length=20),
        ),
    ]
