# Generated by Django 5.2.17 on 2026-10-03 16:44

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationotp_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_contact_name', models.CharField(blank=True, default='Ananya S. (Sister)', max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, default='+91 94471 23456', max_length=50)),
                ('blood_group', models.CharField(blank=True, default='O+ Positive', max_length=20)),
                ('medical_notes', models.TextField(blank=True, default='No major allergies. Carries mild asthma inhaler.')),
                ('dietary_preference', models.CharField(blank=True, default='Traditional Kerala Sadya (Veg)', max_length=100)),
                ('travel_pace', models.CharField(blank=True, default='Balanced (2-3 stops/day)', max_length=100)),
                ('accessibility_required', models.BooleanField(default=False)),
                ('eco_score', models.IntegerField(default=92)),
                ('eco_tier', models.CharField(default='Backwater Guardian', max_length=100)),
                ('trips_completed', models.IntegerField(default=3)),
                ('ev_miles', models.IntegerField(default=142)),
                ('carbon_offset_kg', models.FloatField(default=58.4)),
                ('badges', models.JSONField(blank=True, default=apps.accounts.models.default_profile_badges)),
                ('offline_packages', models.JSONField(blank=True, default=apps.accounts.models.default_offline_packages)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
