# Generated by Django 5.2.17 on 2026-10-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_consent_policy_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
