# Generated by Django 5.2.17 on 2026-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_purge_dummy_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
