# Generated by Django 5.2.17 on 2026-09-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('district', models.CharField(max_length=64)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hero_image', models.URLField()),
                ('gallery_images', models.JSONField(default=list)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('best_season', models.CharField(max_length=128)),
                ('tags', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=dict)),
                ('family_friendly', models.BooleanField(default=True)),
                ('senior_friendly', models.BooleanField(default=True)),
                ('average_stay_days', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opening_time', models.CharField(default='08:00', max_length=10)),
                ('closing_time', models.CharField(default='18:00', max_length=10)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('typical_duration_mins', models.PositiveIntegerField(default=90)),
                ('rain_friendly', models.BooleanField(default=False)),
                ('crowd_profile', models.CharField(default='MODERATE', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination')),
            ],
        ),
    ]
