# Generated by Django 5.2.17 on 2026-09-09 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('currency_code', models.CharField(default='INR', max_length=8)),
                ('currency_symbol', models.CharField(default='₹', max_length=8)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='destinations.country')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.region'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('tourism_board_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='destinations.region')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.state'),
        ),
        migrations.CreateModel(
            name='TravelCircuit',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hero_image', models.URLField()),
                ('gallery_images', models.JSONField(default=list)),
                ('duration_min_days', models.PositiveIntegerField(default=4)),
                ('duration_max_days', models.PositiveIntegerField(default=8)),
                ('recommended_seasons', models.JSONField(default=list)),
                ('terrain_profile', models.CharField(choices=[('COASTAL', 'Coastal & Backwaters'), ('GHATS', 'Western Ghats & Highlands'), ('ALPINE', 'Himalayan Alpine & Valleys'), ('DESERT', 'Desert & Heritage Plains'), ('PLAINS', 'Plateaus & Plains')], default='COASTAL', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('COMING_SOON', 'Coming Soon')], default='ACTIVE', max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='destinations.region')),
                ('states', models.ManyToManyField(blank=True, related_name='circuits', to='destinations.state')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitPerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('plans_generated', models.PositiveIntegerField(default=0)),
                ('plans_accepted', models.PositiveIntegerField(default=0)),
                ('regeneration_count', models.PositiveIntegerField(default=0)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('average_trip_days', models.FloatField(default=5.0)),
                ('average_booking_value_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('weather_substitution_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summary', to='destinations.travelcircuit')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VIEW', 'Circuit Viewed'), ('PLAN_STARTED', 'AI Plan Started for Circuit'), ('PLAN_GENERATED', 'AI Plan Generated'), ('PLAN_ACCEPTED', 'AI Plan Accepted'), ('PLAN_REGENERATED', 'AI Plan Regenerated'), ('BOOKING', 'Circuit Booking Initiated'), ('COMPLETED', 'Circuit Journey Completed')], db_index=True, max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='destinations.travelcircuit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TravelCircuitStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('minimum_stay_days', models.PositiveIntegerField(default=1)),
                ('recommended_stay_days', models.PositiveIntegerField(default=2)),
                ('arrival_buffer_hours', models.FloatField(default=1.5)),
                ('departure_buffer_hours', models.FloatField(default=1.0)),
                ('preferred_transport', models.CharField(choices=[('CAR', 'Private Cab / Car'), ('TRAIN', 'Express Train'), ('FLIGHT', 'Domestic Flight'), ('FERRY', 'Houseboat / Ferry'), ('COMBINED', 'Multi-Modal Transit')], default='CAR', max_length=32)),
                ('stop_highlight', models.CharField(blank=True, default='', max_length=255)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='destinations.travelcircuit')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_stops', to='destinations.destination')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('circuit', 'sequence_order')},
            },
        ),
    ]
