# Generated by Django 5.2.17 on 2026-10-02 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTransferRoute',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('airport_code', models.CharField(choices=[('COK', 'Cochin International Airport (Nedumbassery)'), ('TRV', 'Trivandrum International Airport'), ('CCJ', 'Calicut (Kozhikode) International Airport'), ('CNN', 'Kannur International Airport')], db_index=True, default='COK', max_length=10)),
                ('airport_name', models.CharField(max_length=255)),
                ('destination_name', models.CharField(db_index=True, max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField()),
                ('approx_duration_hours', models.FloatField()),
                ('is_ghat_road', models.BooleanField(default=False)),
                ('toll_and_parking_included', models.BooleanField(default=True)),
                ('sedan_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suv_crysta_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_popular', 'distance_km'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Prime Sedan (Dzire / Etios)'), ('SUV_PREMIUM', 'Premium Mountain SUV (Innova Crysta / Hycross)'), ('TEMPO_TRAVELLER', 'Executive Tempo Traveller (12-17 Seater)'), ('ELECTRIC_EV', 'Green Eco Cab (Nexon / ZS EV)')], default='SUV_PREMIUM', max_length=50)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('passenger_capacity', models.PositiveIntegerField(default=4)),
                ('luggage_capacity', models.PositiveIntegerField(default=3)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_mountain_permit', models.BooleanField(default=True)),
                ('hero_image', models.URLField(max_length=500)),
                ('base_rate_per_km', models.DecimalField(decimal_places=2, default=18.0, max_digits=8)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, default=3800.0, max_digits=10)),
                ('driver_bata_per_day', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('features', models.JSONField(default=list)),
                ('rating', models.FloatField(default=4.95)),
                ('trip_count', models.PositiveIntegerField(default=140)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['passenger_capacity'],
            },
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('booking_type', models.CharField(choices=[('AIRPORT_PICKUP', 'Airport Pickup & Transfer'), ('AIRPORT_DROP', 'Airport Drop-off'), ('MULTI_DAY_RENTAL', 'Multi-Day Chauffeur Rental'), ('INTERCITY_DROP', 'Intercity One-Way Drop')], default='AIRPORT_PICKUP', max_length=50)),
                ('traveler_name', models.CharField(max_length=150)),
                ('traveler_email', models.EmailField(blank=True, default='', max_length=254)),
                ('traveler_phone', models.CharField(max_length=30)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=20)),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('passenger_count', models.PositiveIntegerField(default=2)),
                ('luggage_count', models.PositiveIntegerField(default=2)),
                ('flight_number', models.CharField(blank=True, default='', max_length=50)),
                ('nameboard_text', models.CharField(blank=True, default='', max_length=150)),
                ('flight_delayed_protection', models.BooleanField(default=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAY_TO_DRIVER', 'Pay directly to Chauffeur (Cash / UPI)'), ('PAID_ONLINE', 'Paid Online in Advance'), ('PENDING', 'Payment Pending')], default='PAY_TO_DRIVER', max_length=50)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('ON_THE_WAY', 'Chauffeur En Route'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=50)),
                ('assigned_driver_name', models.CharField(default='Rajesh Kumar', max_length=150)),
                ('assigned_driver_phone', models.CharField(default='+91 94470 54321', max_length=30)),
                ('assigned_driver_whatsapp', models.CharField(default='+919447054321', max_length=30)),
                ('vehicle_plate_number', models.CharField(default='KL-07-CD-4589', max_length=30)),
                ('special_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='transport.vehiclecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
